CREATE OR REPLACE DIRECTORY
  external_tables_dir AS &1;
  /
  
GRANT READ,WRITE ON DIRECTORY
  external_tables_dir TO system;
  /
  
  create or replace package pkg_corruption_perception
  as
  procedure load_data_src(file_name varchar2,delimiters varchar2);
  end;
  /
  
  create or replace package body pkg_corruption_perception
  as
  procedure load_data_src 
(
  file_name VARCHAR2,
  delimiters VARCHAR2
)
  as
 BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE Corruption_perception
(
  COUNTRY VARCHAR2(128),
ISO3 VARCHAR2(128),
REGION VARCHAR2(128),
CPI_SCORE_2020 NUMBER(38),
RANK NUMBER(38),
STANDARD_ERROR NUMBER(38, 7),
NUMBER_OF_SOURCES NUMBER(38),
LOWER_CI NUMBER(38, 5),
UPPER_CI NUMBER(38, 5),
AFRICAN_DEVELOPMENT_BANK_CPIA NUMBER(38),
BERTELSMANN_SUSTAINABLE_INDEX NUMBER(38),
BERTELSMANN_TRANSFORMAT_INDEX NUMBER(38),
ECONOMIST_UNIT_COUNTRY_RATINGS NUMBER(38),
FREEDOM_NATIONS_IN_TRANSIT NUMBER(38),
GLOBAL_INSIGHT_RISK_RATINGS NUMBER(38),
IMD_WORLD_YEARBOOK NUMBER(38),
PERC_ASIA_RISK_GUIDE NUMBER(38),
PRS_INTERNATIONAL_RISK_GUIDE NUMBER(38),
VARIETIES_OF_DEMOCRACY_PROJECT NUMBER(38),
WORLD_BANK_CPIA NUMBER(38),
WORLD_FORUM_EOS NUMBER(38),
WORLD_RULE_OF_LAW_INDEX NUMBER(38)
)
ORGANIZATION EXTERNAL
(
  TYPE ORACLE_LOADER
  DEFAULT DIRECTORY DATA_DIR
  ACCESS PARAMETERS
  (FIELDS TERMINATED BY ''' || delimiters || ''')
  LOCATION (''' || file_name || ''')
)';
  end;
  end;
  /